openapi: 3.1.0
info:
  title: API
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /user:
    post:
      operationId: createUser
      summary: Creates a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: The created user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  /room:
    post:
      operationId: createRoom
      summary: Creates a new room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                  nullable: true
      responses:
        '200':
          description: The created room
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RoomResponse'
  /room/search:
    get:
      operationId: searchRoom
      summary: Searches for a room
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
      responses:
        '200':
          description: The search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoomResponse'
components:
  schemas:
    UserResponse:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    RoomResponse:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        description:
          type: string
          nullable: true
